# Generated by Django 3.2.16 on 2022-12-15 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default='2021-10-10 10:00:00')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Dentista', 'Dentista'), ('Cardiología', 'Cardiología'), ('Traumatología', 'Traumatología'), ('Neurología', 'Neurología'), ('Dermatología', 'Dermatología'), ('Oftalmología', 'Oftalmología'), ('Pedicuría', 'Pedicuría')], max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Hospital de Niños', 'Hospital de Niños'), ('Hospital de Niños de la Maternidad', 'Hospital de Niños de la Maternidad'), ('Hospital Pirovano', 'Hospital Pirovano'), ('Hospital Vicente López', 'Hospital Vicente López'), ('Hospital de Clínicas', 'Hospital de Clínicas'), ('Hospital de Clínicas de la Universidad de Buenos Aires', 'Hospital de Clínicas de la Universidad de Buenos Aires')], default='Hospital de Niños', max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('telefono', models.CharField(max_length=120)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=0)),
                ('agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.agenda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.especialidades'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.hospitales'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
