# Generated by Django 3.2.16 on 2022-11-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_agenda_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidades',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
    ]
